version: 2
updates:
  - package-ecosystem: npm
    labels: []
    directory: /crates/www
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: cargo
    labels: []
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    labels: []
    directory: /
    schedule:
      interval: weekly
